import {
  MdTrackChanges, MdExplore, MdMenuBook, MdAutoAwesome, MdPsychology,
  MdSportsEsports, MdAssignmentTurnedIn, MdLocalFireDepartment, MdCalendarMonth,
  MdWorkspacePremium, MdStart, MdCategory, MdEmojiEvents, MdRocketLaunch,
  MdCollections, MdLoop, MdBolt, MdGpsFixed, MdMilitaryTech, MdTrendingUp,
  MdTimeline, MdCelebration, MdEventRepeat, MdStar,
  MdSearch, MdCollectionsBookmark, MdToys, MdVideogameAsset, MdQuiz,
  MdFactCheck, MdVerified, MdSavings, MdAttachMoney, MdMonetizationOn,
  MdStairs, MdNearMe, MdDashboard, MdMap, MdLayers, MdInsights, MdUpgrade,
  MdWhatshot, MdWidgets
} from 'react-icons/md';

export const MEDAL_ICONS = {
  primer_paso: MdTrackChanges,
  explorador: MdExplore,
  lector_aplicado: MdMenuBook,
  curioso_incansable: MdSearch,
  lector_dedicado: MdCollectionsBookmark,
  maestro_juegos: MdSportsEsports,
  maestro_ludico: MdToys,
  gamer_pro: MdVideogameAsset,
  puntaje_perfecto_juego: MdEmojiEvents,
  evaluador_experto: MdAssignmentTurnedIn,
  examinador_frecuente: MdQuiz,
  evaluador_dedicado: MdFactCheck,
  puntaje_perfecto_evaluacion: MdVerified,
  recolector_puntos: MdSavings,
  superestudiante: MdRocketLaunch,
  acumulador_puntos: MdAttachMoney,
  millonario_puntos: MdMonetizationOn,
  leyenda: MdWorkspacePremium,
  ritmo_escalera: MdStairs,
  avance_medio: MdTrendingUp,
  casi_maestro: MdNearMe,
  explorador_modulos: MdCategory,
  iniciador_modulos: MdDashboard,
  explorador_total: MdMap,
  gran_comienzo: MdStart,
  dominio_modulo: MdGpsFixed,
  completador_modulos: MdLayers,
  rey_conocimiento: MdEmojiEvents,
  estrella_conocimiento: MdAutoAwesome,
  cerebro_brillante: MdPsychology,
  mente_rapida: MdBolt,
  campeon: MdEmojiEvents,
  experto: MdMilitaryTech,
  rendimiento_alto: MdInsights,
  perfeccionista: MdWorkspacePremium,
  estrella_rendimiento: MdStar,
  triple_estrella: MdStar,
  racha_inicial: MdLocalFireDepartment,
  constancia: MdCalendarMonth,
  aprendiz_constante: MdEventRepeat,
  racha_tres_dias: MdWhatshot,
  racha_siete_dias: MdBolt,
  sin_rendirse: MdLoop,
  desafio_superado: MdTimeline,
  superando_limites: MdTrendingUp,
  buscador_de_mejora: MdUpgrade,
  coleccionista: MdCollections,
  gran_aprendiz: MdTrendingUp,
  lo_logre: MdCelebration,
  multitalento: MdWidgets
};

export const MEDAL_CATEGORIES = {
  contenidos: 'Contenidos',
  juegos: 'Juegos',
  evaluaciones: 'Evaluaciones',
  puntos: 'Puntos',
  progreso: 'Progreso',
  modulos: 'Módulos',
  rendimiento: 'Rendimiento',
  constancia: 'Constancia',
  superacion: 'Superación',
  uso_plataforma: 'Uso de la plataforma'
};